baseURL = "https://KristenTidmuss.dev"
languageCode = "en-us"
title = "Kristen Tidmuss"
theme = "PaperModTheme"

[params]
defaultTheme = "dark"
disableThemeToggle = true
ShowReadingTime = true
env = "production"

[params.profileMode]
enabled = true
title = "Kristen Tidmuss"
imageUrl = "/images/avatar/Avatar-Color-NoBG.png"
imageTitle = "KristenTidmuss"
imageWidth = 256
imageHeight = 256

  [[params.profileMode.buttons]]
  name = "About"
  url = "/about"

  [[params.profileMode.buttons]]
  name = "Projects"
  url = "/projects"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/KristenTidmuss"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/kristen-tidmuss-116ab8105/"

[assets]
favicon = "https://kristentidmuss.dev/favicon.ico"
favicon16x16 = "https://kristentidmuss.dev/favicon-16x16.png"
favicon32x32 = "https://kristentidmuss.dev/favicon-32x32.png"
apple_touch_icon = "https://kristentidmuss.dev/apple-touch-icon.png"